- name: Cluster Context
  gather_facts: false
  connection: local
  hosts: localhost
  vars:
    log: [] # used for storing shell command data
    env:    # used as shell environment
      OCM_ENVIRONMENT: '{{OCM_ENVIRONMENT | default("staging") }}'
      OCM_URLS:
        production: https://api.openshift.com
        staging: https://api.stage.openshift.com
        integration: https://api.integration.openshift.com
      CLUSTER: '{{ CLUSTER }}'
  tasks:
    - name: Cluster Context
      block:
        - include_tasks: tasks/cluster_context/main.yml
      always:
        - name: Create report
          include_tasks: tasks/common/create_report.yml
          vars:
            template_file: cluster_context.md.j2
            out_path: reports/cluster_context/{{ env.CLUSTER_NAME | default('not_found') }}
