- name: Attempt login to cluster hive via backplane
  include_tasks: tasks/common/shell.yml
  vars:
    description: Attempt login to cluster hive via backplane
    ignore_errors: true
    command: |
      ocm-backplane login {{ env.HIVE_NAME }}

- name: Set logged in to hive
  set_fact:
    loggedin_hive: "{{ false if cmd.rc else true }}"
    UHC_NS: uhc-{{ env.OCM_ENVIRONMENT }}-{{ env.CLUSTER_ID }}

- name: "Tasks on hive"
  when: loggedin_hive
  block:
    - name: Get cluster deployment in
      include_tasks: tasks/common/shell.yml
      vars:
        description: Get cluster deployment
        ignore_errors: true
        command: |
          oc get clusterdeployment -n {{ UHC_NS }}

    - name: Get cluster project claim
      include_tasks: tasks/common/shell.yml
      vars:
        description: Get cluster project claim
        ignore_errors: true
        command: |
          oc get projectclaim -n {{ UHC_NS }}

    - name: Get cluster install pod
      include_tasks: tasks/common/shell.yml
      vars:
        description: Get cluster install pod
        ignore_errors: true
        command: |
          oc get pod -n {{ UHC_NS }}

    - name: Get cluster clustersync
      include_tasks: "tasks/common/shell.yml"
      vars:
        description: Get clustersync
        ignore_errors: true
        command: |
          oc get clustersync -n {{ UHC_NS }} -o json | jq -r .items[].status.conditions

    - name: Get aws-account-operator account status
      include_tasks: "tasks/common/shell.yml"
      vars:
        description: Get aws-account-operator account status
        ignore_errors: true
        command: |
          oc get account -n aws-account-operator -o json | jq -r \
          '.items[] | select(.spec.claimLinkNamespace=="{{ UHC_NS }}").status'

    - name: Get certman certificaterequest
      include_tasks: tasks/common/shell.yml
      vars:
        description: Get certman certificaterequest
        ignore_errors: true
        command: |
          oc get certificaterequest.certman.managed.openshift.io -n {{ UHC_NS }} -o json
        stdout_to_json: true

    - name: Get certman-operator logs
      include_tasks: tasks/common/shell.yml
      vars:
        description: Get certman-operator logs
        ignore_errors: true
        command: |
          oc logs -n certman-operator -l name=certman-operator --tail=-1 | grep {{ env.CLUSTER_ID }}
      when: cmd.json.items['status'] is defined

    - name:
      include_tasks: tasks/common/shell.yml
      vars:
        description: Get machine pool
        ignore_errors: true
        command: |
          oc get MachinePool -n {{ UHC_NS }} -o json | jq -r .status.conditions
        stdout_to_json: true