- name: Login to ocm prod
  include_tasks: tasks/common/shell.yml
  vars:
    description: Login to ocm prod
    command: |
      ocm login --token=$OFFLINE_ACCESS_TOKEN --url=production
    template_name: common/blank.md.j2

- name: Attempt login to cluster hive via backplane
  include_tasks: tasks/common/shell.yml
  vars:
    description: Attempt login to cluster hive via backplane
    ignore_errors: true
    command: |
      ocm-backplane login {{ env.HIVE_NAME }}

- name: Set logged in to hive
  set_fact:
    loggedin_hive: "{{ false if cmd.rc else true }}"
    uhc_ns: uhc-{{ env.OCM_ENVIRONMENT }}-{{ env.CLUSTER_ID }}

- name: "Tasks on hive"
  when: loggedin_hive
  block:
    - name: Get cluster deployment in
      include_tasks: tasks/common/shell.yml
      vars:
        description: Get cluster deployment
        command: |
          oc get clusterdeployment -n {{ uhc_ns }}

    - name: Get cluster project claim
      include_tasks: tasks/common/shell.yml
      vars:
        description: Get cluster project claim
        command: |
          oc get projectclaim -n {{ uhc_ns }}

    - name: Get cluster install pod
      include_tasks: tasks/common/shell.yml
      vars:
        description: Get cluster install pod
        command: |
          oc get pod -n {{ uhc_ns }}

    - name: Get cluster clustersync
      include_tasks: "tasks/common/shell.yml"
      vars:
        description: Get clustersync
        command: |
          oc get clustersync -n {{ uhc_ns }} -o json | jq -r .items[].status.conditions

    - name: Get aws-account-operator account status
      include_tasks: "tasks/common/shell.yml"
      vars:
        description: Get aws-account-operator account status
        command: |
          oc get account -n aws-account-operator -o json | jq -r \
          '.items[] | select(.spec.claimLinkNamespace=="{{ uhc_ns }}").status'

    - name: Get certman certificaterequest
      include_tasks: tasks/common/shell.yml
      vars:
        description: Get certman certificaterequest
        ignore_errors: true
        command: |
          oc get certificaterequest.certman.managed.openshift.io -n {{ uhc_ns }} -o json
        stdout_to_json: true

    - name: Get certman-operator logs
      include_tasks: tasks/common/shell.yml
      vars:
        description: Get certman-operator logs
        ignore_errors: true
        command: |
          oc logs -n certman-operator -l name=certman-operator --tail=-1 | grep {{ env.CLUSTER_ID }}
      when: cmd.json.items['status'] is defined
