- name: Set ocm config url for {{ env.OCM_ENVIRONMENT }}
  include_tasks: tasks/common/shell.yml
  vars:
    description: Set ocm config url for {{ env.OCM_ENVIRONMENT }}
    command: |
      ocm config set url {{ env.OCM_URLS[env.OCM_ENVIRONMENT] }}
    template_name: common/blank.md.j2

- name: Attempt login to cluster mc via backplane
  include_tasks: tasks/common/shell.yml
  vars:
    description: Attempt login to cluster mc via backplane
    ignore_errors: true
    command: |
      ocm-backplane login {{ env.MC_NAME }}

- name: Set logged in to mc
  set_fact:
    loggedin_mc: "{{ false if cmd.rc else true }}"

- name: "Tasks on mc"
  when: loggedin_mc
  block:
    - name: Get hypershift operator logs containing cluster id
      include_tasks: tasks/common/shell.yml
      vars:
        description: Hypershift operator logs containing cluster id
        ignore_errors: true
        command: |
          oc logs -n hypershift -l name=operator --since 48h | grep {{ env.CLUSTER_ID }}

    - name: Get projects with cluster id
      include_tasks: tasks/common/shell.yml
      vars:
        description: Projects with cluster id
        command: |
          oc get project | grep {{ env.CLUSTER_ID }}

    - name: Get project status
      include_tasks: tasks/common/shell.yml
      vars:
        description: Project status
        command: |
          oc get project {{ env.HCP_NAMESPACE }} -o json | jq -r .status

    - name: Get pods in hcp namespace
      include_tasks: tasks/common/shell.yml
      vars:
        description: Pods in hcp namespace
        command: |
          oc get po -n {{ env.HCP_NAMESPACE }}

    - name: Get warning events in hcp namespace
      include_tasks: tasks/common/shell.yml
      vars:
        description: Warning events hcp namespace
        command: |
          kubectl events -n {{ env.HCP_NAMESPACE }} --types=Warning

    - name: Get hypershift worker nodes
      include_tasks: tasks/common/shell.yml
      vars:
        description: Hypershift worker nodes
        command: |
          oc get machinedeployment -o wide -n {{ env.HCP_NAMESPACE }}

    - name: Get aws machines
      include_tasks: tasks/common/shell.yml
      vars:
        description: Aws machines
        command: |
          oc get awsmachines -n {{ env.HCP_NAMESPACE }}

    - name: Get machine.cluster
      include_tasks: tasks/common/shell.yml
      vars:
        description: Machine.cluster
        command: |
          oc get machine.cluster.x-k8s.io -n {{ env.HCP_NAMESPACE }}

    - name: Get clusters.cluster
      include_tasks: tasks/common/shell.yml
      vars:
        description: Clusters.cluster
        command: |
          oc get clusters.cluster.x-k8s.io -n {{ env.HCP_NAMESPACE }}

    - name: Get packages
      include_tasks: tasks/common/shell.yml
      vars:
        description: Packages
        command: |
          oc get packages -n {{ env.HCP_NAMESPACE }}
        ignore_errors: true

    - name: Get hostedcluster status.conditions
      include_tasks: tasks/common/shell.yml
      vars:
        description: Hostedcluster status.conditions
        command: |
          oc get hostedcluster -n ocm-$OCM_ENVIRONMENT-$CLUSTER_ID -o json | jq -r .items[].status.conditions

    - name: Get vpcendpoints status.conditions
      include_tasks: tasks/common/shell.yml
      vars:
        description: Vpcendpoints status.conditions
        command: |
          oc get vpcendpoints -n {{ env.HCP_NAMESPACE }} private-hcp -o json | jq -r .status.conditions

    - name: Get awsendpointservices status.conditions
      include_tasks: tasks/common/shell.yml
      vars:
        description: Awsendpointservices status.conditions
        command: |
          oc get awsendpointservices -n {{ env.HCP_NAMESPACE }} private-router -o json | jq -r .status.conditions

    - name: Get control-plane-operator logs
      include_tasks: tasks/common/shell.yml
      vars:
        description: Control-plane-operator logs
        command: |
          oc logs -n {{ env.HCP_NAMESPACE }} -l app=control-plane-operator -c control-plane-operator --since=30m

    - name: Get kube-apiserver logs
      include_tasks: tasks/common/shell.yml
      vars:
        description: Kube-apiserver logs
        command: |
          oc logs -n {{ env.HCP_NAMESPACE }} -l app=kube-apiserver -c kube-apiserver --since=30m
